// ================================================
// RECIPE DISPLAY UI SYSTEM
// ================================================

let selectedRecipesThisWeek = [];
let currentFilters = {
    category: 'all',
    vegetarian: false,
    vegan: false,
    nutFree: false,
    dairyFree: false,
    glutenFree: false
};

// ===================================
// INITIALIZE RECIPE LIBRARY TAB
// ===================================

function initializeRecipeLibrary() {
    // Add recipe library HTML to recipes content
    const recipesContent = document.getElementById('recipesContent');
    
    // Create tabs container
    const tabsHTML = `
        <div class="recipes-tabs" style="display: flex; gap: 10px; margin-bottom: 20px; background: white; padding: 15px; border-radius: 12px;">
            <button class="recipe-tab active" data-tab="library" style="flex: 1; padding: 12px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; font-size: 15px;">
                📚 Recipe Library
            </button>
            <button class="recipe-tab" data-tab="thisweek" style="flex: 1; padding: 12px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; background: #f0f0f0; color: #333; font-size: 15px;">
                🍽️ This Week
            </button>
        </div>
        
        <!-- Recipe Library Tab -->
        <div id="recipeLibraryTab" class="recipe-tab-content active">
            <!-- Filters -->
            <div class="recipe-filters" style="background: white; padding: 20px; border-radius: 12px; margin-bottom: 20px;">
                <div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: center; margin-bottom: 15px;">
                    <select id="categoryFilter" style="padding: 10px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 14px; font-weight: 600; min-width: 150px;">
                        <option value="all">All Categories</option>
                        <option value="breakfast">🍳 Breakfast</option>
                        <option value="batch">🍲 Batch Cook</option>
                    </select>
                    
                    <button onclick="clearFilters()" style="padding: 10px 15px; background: #f44336; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; font-size: 14px;">
                        ✕ Clear Filters
                    </button>
                </div>
                
                <div class="dietary-filters" style="display: flex; gap: 15px; flex-wrap: wrap;">
                    <label style="display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 8px 12px; background: #f8f9fa; border-radius: 8px;">
                        <input type="checkbox" id="filterVegetarian" value="vegetarian" style="width: 18px; height: 18px;">
                        <span style="font-weight: 600;">🥬 Vegetarian</span>
                    </label>
                    <label style="display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 8px 12px; background: #f8f9fa; border-radius: 8px;">
                        <input type="checkbox" id="filterVegan" value="vegan" style="width: 18px; height: 18px;">
                        <span style="font-weight: 600;">🌱 Vegan</span>
                    </label>
                    <label style="display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 8px 12px; background: #f8f9fa; border-radius: 8px;">
                        <input type="checkbox" id="filterNutFree" value="nutFree" style="width: 18px; height: 18px;">
                        <span style="font-weight: 600;">🥜 Nut-free</span>
                    </label>
                    <label style="display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 8px 12px; background: #f8f9fa; border-radius: 8px;">
                        <input type="checkbox" id="filterDairyFree" value="dairyFree" style="width: 18px; height: 18px;">
                        <span style="font-weight: 600;">🥛 Dairy-free</span>
                    </label>
                    <label style="display: flex; align-items: center; gap: 8px; cursor: pointer; padding: 8px 12px; background: #f8f9fa; border-radius: 8px;">
                        <input type="checkbox" id="filterGlutenFree" value="glutenFree" style="width: 18px; height: 18px;">
                        <span style="font-weight: 600;">🌾 Gluten-free</span>
                    </label>
                </div>
            </div>
            
            <!-- Recipe Grid -->
            <div id="recipeGrid" class="recipe-grid" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px;">
                <!-- Cards generated by JS -->
            </div>
        </div>
        
        <!-- This Week Tab -->
        <div id="thisWeekTab" class="recipe-tab-content" style="display: none;">
            <div id="thisWeekRecipes" style="background: white; padding: 30px; border-radius: 12px;">
                <p style="text-align: center; color: #999; font-size: 16px;">No recipes selected this week. Import a schedule with recipes to see them here!</p>
            </div>
        </div>
    `;
    
    recipesContent.innerHTML = tabsHTML;
    
    // Setup event listeners
    setupRecipeTabListeners();
    setupFilterListeners();
    
    // Initial render
    renderRecipeGrid();
    
    console.log('✅ Recipe Library initialized!');
}

// ===================================
// TAB SWITCHING
// ===================================

function setupRecipeTabListeners() {
    document.querySelectorAll('.recipe-tab').forEach(tab => {
        tab.addEventListener('click', () => {
            const tabName = tab.dataset.tab;
            
            // Update tab buttons
            document.querySelectorAll('.recipe-tab').forEach(t => {
                t.classList.remove('active');
                t.style.background = '#f0f0f0';
                t.style.color = '#333';
            });
            tab.classList.add('active');
            tab.style.background = 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)';
            tab.style.color = 'white';
            
            // Update tab content
            document.querySelectorAll('.recipe-tab-content').forEach(content => {
                content.style.display = 'none';
            });
            
            if (tabName === 'library') {
                document.getElementById('recipeLibraryTab').style.display = 'block';
            } else {
                document.getElementById('thisWeekTab').style.display = 'block';
                renderThisWeekRecipes();
            }
        });
    });
}

// ===================================
// FILTER SYSTEM
// ===================================

function setupFilterListeners() {
    // Category filter
    document.getElementById('categoryFilter').addEventListener('change', (e) => {
        currentFilters.category = e.target.value;
        renderRecipeGrid();
    });
    
    // Dietary filters
    document.getElementById('filterVegetarian').addEventListener('change', (e) => {
        currentFilters.vegetarian = e.target.checked;
        renderRecipeGrid();
    });
    
    document.getElementById('filterVegan').addEventListener('change', (e) => {
        currentFilters.vegan = e.target.checked;
        renderRecipeGrid();
    });
    
    document.getElementById('filterNutFree').addEventListener('change', (e) => {
        currentFilters.nutFree = e.target.checked;
        renderRecipeGrid();
    });
    
    document.getElementById('filterDairyFree').addEventListener('change', (e) => {
        currentFilters.dairyFree = e.target.checked;
        renderRecipeGrid();
    });
    
    document.getElementById('filterGlutenFree').addEventListener('change', (e) => {
        currentFilters.glutenFree = e.target.checked;
        renderRecipeGrid();
    });
}

function clearFilters() {
    currentFilters = {
        category: 'all',
        vegetarian: false,
        vegan: false,
        nutFree: false,
        dairyFree: false,
        glutenFree: false
    };
    
    document.getElementById('categoryFilter').value = 'all';
    document.getElementById('filterVegetarian').checked = false;
    document.getElementById('filterVegan').checked = false;
    document.getElementById('filterNutFree').checked = false;
    document.getElementById('filterDairyFree').checked = false;
    document.getElementById('filterGlutenFree').checked = false;
    
    renderRecipeGrid();
}

function applyFilters(recipes) {
    return recipes.filter(recipe => {
        // Category filter
        if (currentFilters.category !== 'all' && recipe.category !== currentFilters.category) {
            return false;
        }
        
        // Dietary filters
        if (currentFilters.vegetarian && !recipe.dietary.vegetarian) return false;
        if (currentFilters.vegan && !recipe.dietary.vegan) return false;
        if (currentFilters.nutFree && recipe.dietary.nuts) return false;
        if (currentFilters.dairyFree && recipe.dietary.dairy) return false;
        if (currentFilters.glutenFree && recipe.dietary.gluten) return false;
        
        return true;
    });
}

// ===================================
// RECIPE GRID RENDERING
// ===================================

function renderRecipeGrid() {
    const grid = document.getElementById('recipeGrid');
    const allRecipes = getAllRecipes();
    const recipesArray = Object.values(allRecipes);
    const filtered = applyFilters(recipesArray);
    
    if (filtered.length === 0) {
        grid.innerHTML = `
            <div style="grid-column: 1 / -1; text-align: center; padding: 60px 20px;">
                <p style="font-size: 48px; margin: 0 0 20px 0;">🔍</p>
                <p style="font-size: 18px; color: #666; margin: 0;">No recipes match your filters</p>
                <button onclick="clearFilters()" style="margin-top: 20px; padding: 12px 24px; background: #667eea; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600;">
                    Clear Filters
                </button>
            </div>
        `;
        return;
    }
    
    let html = '';
    filtered.forEach(recipe => {
        html += createRecipeCard(recipe);
    });
    
    grid.innerHTML = html;
}

function createRecipeCard(recipe) {
    const tags = [];
    if (recipe.dietary.vegetarian) tags.push('🥬 Vegetarian');
    if (recipe.dietary.vegan) tags.push('🌱 Vegan');
    if (!recipe.dietary.nuts) tags.push('🥜 Nut-free');
    if (!recipe.dietary.dairy) tags.push('🥛 Dairy-free');
    if (!recipe.dietary.gluten) tags.push('🌾 Gluten-free');
    
    const categoryBadge = recipe.category === 'breakfast' ? '🍳 Breakfast' : '🍲 Batch Cook';
    
    return `
        <div class="recipe-card" onclick="openRecipeModal('${recipe.id}')" style="background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); cursor: pointer; transition: all 0.3s ease;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; color: white; text-align: center;">
                <div style="font-size: 48px; margin-bottom: 10px;">${recipe.display.emoji}</div>
                <div style="background: rgba(255,255,255,0.2); padding: 5px 12px; border-radius: 20px; display: inline-block; font-size: 12px; font-weight: 600; margin-bottom: 10px;">
                    ${categoryBadge}
                </div>
                <h3 style="margin: 10px 0 0 0; font-size: 18px;">${recipe.name}</h3>
            </div>
            
            <div style="padding: 20px;">
                <p style="color: #666; font-size: 14px; line-height: 1.5; margin: 0 0 15px 0;">${recipe.display.description}</p>
                
                <div style="display: flex; gap: 8px; margin-bottom: 15px; flex-wrap: wrap;">
                    <span style="background: #e8f5e9; color: #2e7d32; padding: 5px 10px; border-radius: 6px; font-size: 12px; font-weight: 600;">
                        ⏱️ ${recipe.prepTime} + ${recipe.cookTime}
                    </span>
                    <span style="background: #fff3e0; color: #e65100; padding: 5px 10px; border-radius: 6px; font-size: 12px; font-weight: 600;">
                        🍽️ Serves ${recipe.serves}
                    </span>
                </div>
                
                <div style="display: flex; gap: 5px; flex-wrap: wrap;">
                    ${tags.map(tag => `<span style="background: #f0f0f0; padding: 4px 8px; border-radius: 4px; font-size: 11px; color: #666;">${tag}</span>`).join('')}
                </div>
            </div>
        </div>
    `;
}

// ===================================
// RECIPE MODAL
// ===================================

function openRecipeModal(recipeId) {
    const recipe = getRecipe(recipeId);
    if (!recipe) {
        alert('Recipe not found!');
        return;
    }
    
    const modal = document.createElement('div');
    modal.id = 'recipeModal';
    modal.className = 'modal active';
    modal.innerHTML = `
        <div class="modal-content" style="max-width: 700px; max-height: 85vh; overflow-y: auto;">
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 25px; border-radius: 12px 12px 0 0; margin: -30px -30px 20px -30px; color: white; text-align: center;">
                <div style="font-size: 64px; margin-bottom: 10px;">${recipe.display.emoji}</div>
                <h2 style="margin: 0 0 10px 0; color: white; font-size: 28px;">${recipe.name}</h2>
                <p style="margin: 0; opacity: 0.9; font-size: 14px;">${recipe.display.description}</p>
                <div style="display: flex; gap: 15px; justify-content: center; margin-top: 15px;">
                    <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 8px; font-size: 14px;">
                        ⏱️ ${recipe.prepTime} + ${recipe.cookTime}
                    </span>
                    <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 8px; font-size: 14px;">
                        🍽️ Serves ${recipe.serves}
                    </span>
                </div>
            </div>
            
            <!-- Ingredients -->
            <div style="margin-bottom: 25px;">
                <h3 style="color: #667eea; margin: 0 0 15px 0; font-size: 20px;">🛒 Ingredients</h3>
                <ul style="list-style: none; padding: 0; margin: 0;">
                    ${recipe.display.ingredients.map(ing => `
                        <li style="padding: 10px; background: #f8f9fa; margin-bottom: 8px; border-radius: 8px; display: flex; align-items: center; gap: 10px;">
                            <span style="width: 8px; height: 8px; background: #667eea; border-radius: 50%; flex-shrink: 0;"></span>
                            <span style="color: #2c3e50;">${ing}</span>
                        </li>
                    `).join('')}
                </ul>
            </div>
            
            <!-- Instructions -->
            <div style="margin-bottom: 25px;">
                <h3 style="color: #667eea; margin: 0 0 15px 0; font-size: 20px;">👨‍🍳 Instructions</h3>
                <ol style="padding-left: 20px; margin: 0;">
                    ${recipe.display.instructions.map(step => `
                        <li style="padding: 12px 0; color: #2c3e50; line-height: 1.6; border-bottom: 1px solid #f0f0f0;">
                            ${step}
                        </li>
                    `).join('')}
                </ol>
            </div>
            
            <!-- Tips -->
            ${recipe.display.tips && recipe.display.tips.length > 0 ? `
                <div style="margin-bottom: 25px; background: #fff3e0; padding: 20px; border-radius: 12px; border-left: 4px solid #ff9800;">
                    <h3 style="color: #e65100; margin: 0 0 15px 0; font-size: 18px;">💡 Pro Tips</h3>
                    <ul style="margin: 0; padding-left: 20px;">
                        ${recipe.display.tips.map(tip => `
                            <li style="color: #5d4037; margin-bottom: 8px; line-height: 1.5;">${tip}</li>
                        `).join('')}
                    </ul>
                </div>
            ` : ''}
            
            <!-- Video & Nutrition -->
            <div style="display: flex; gap: 15px; flex-wrap: wrap; margin-bottom: 25px;">
                ${recipe.display.video ? `
                    <a href="${recipe.display.video}" target="_blank" style="flex: 1; min-width: 200px; display: flex; align-items: center; gap: 10px; background: linear-gradient(135deg, #ff0000 0%, #cc0000 100%); color: white; padding: 12px 20px; border-radius: 10px; text-decoration: none; font-weight: 600; box-shadow: 0 4px 12px rgba(255,0,0,0.3);">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="white">
                            <path d="M8 5v14l11-7z"/>
                        </svg>
                        <span>Watch Video</span>
                    </a>
                ` : ''}
                
                ${recipe.display.nutrition ? `
                    <div style="flex: 1; min-width: 200px; background: #e8f5e9; padding: 12px 20px; border-radius: 10px; display: flex; align-items: center; gap: 10px;">
                        <span style="font-size: 20px;">📊</span>
                        <span style="color: #2e7d32; font-size: 13px; font-weight: 600;">${recipe.display.nutrition}</span>
                    </div>
                ` : ''}
            </div>
            
            <!-- Buttons -->
            <div style="display: flex; gap: 10px;">
                <button onclick="closeRecipeModal()" style="flex: 1; padding: 14px; background: #f0f0f0; color: #333; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; font-size: 15px;">
                    ← Back to Library
                </button>
                <button onclick="addRecipeToThisWeek('${recipe.id}')" style="flex: 2; padding: 14px; background: linear-gradient(135deg, #4caf50 0%, #45a049 100%); color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; font-size: 15px;">
                    ✅ Add to This Week
                </button>
            </div>
        </div>
    `;
    
    document.body.appendChild(modal);
}

function closeRecipeModal() {
    const modal = document.getElementById('recipeModal');
    if (modal) modal.remove();
}

// ===================================
// THIS WEEK TAB
// ===================================

function addRecipeToThisWeek(recipeId) {
    if (!selectedRecipesThisWeek.includes(recipeId)) {
        selectedRecipesThisWeek.push(recipeId);
        saveSelectedRecipes();
        closeRecipeModal();
        
        // Switch to This Week tab
        document.querySelector('.recipe-tab[data-tab="thisweek"]').click();
        
        alert('✅ Recipe added to This Week!');
    } else {
        alert('This recipe is already in This Week!');
    }
}

function removeRecipeFromThisWeek(recipeId) {
    selectedRecipesThisWeek = selectedRecipesThisWeek.filter(id => id !== recipeId);
    saveSelectedRecipes();
    renderThisWeekRecipes();
}

function renderThisWeekRecipes() {
    const container = document.getElementById('thisWeekRecipes');
    
    if (selectedRecipesThisWeek.length === 0) {
        container.innerHTML = `
            <div style="text-align: center; padding: 60px 20px;">
                <p style="font-size: 48px; margin: 0 0 20px 0;">🍽️</p>
                <p style="font-size: 18px; color: #666; margin: 0 0 10px 0;">No recipes selected this week</p>
                <p style="font-size: 14px; color: #999; margin: 0 0 20px 0;">Browse the Recipe Library and add recipes, or import a schedule with recipes!</p>
                <button onclick="document.querySelector('.recipe-tab[data-tab=\\'library\\']').click()" style="padding: 12px 24px; background: #667eea; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600;">
                    Browse Recipe Library
                </button>
            </div>
        `;
        return;
    }
    
    let html = '<div style="display: grid; gap: 25px;">';
    
    selectedRecipesThisWeek.forEach(recipeId => {
        const recipe = getRecipe(recipeId);
        if (!recipe) return;
        
        html += `
            <div style="background: white; border-radius: 12px; padding: 25px; box-shadow: 0 2px 12px rgba(0,0,0,0.08);">
                <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 20px;">
                    <div style="display: flex; align-items: center; gap: 15px;">
                        <div style="font-size: 48px;">${recipe.display.emoji}</div>
                        <div>
                            <h3 style="margin: 0 0 5px 0; color: #2c3e50; font-size: 22px;">${recipe.name}</h3>
                            <p style="margin: 0; color: #666; font-size: 14px;">${recipe.display.description}</p>
                        </div>
                    </div>
                    <button onclick="removeRecipeFromThisWeek('${recipe.id}')" style="background: #ff6b6b; color: white; border: none; padding: 8px 12px; border-radius: 6px; cursor: pointer; font-weight: 600; font-size: 14px;">
                        ✕ Remove
                    </button>
                </div>
                
                <button onclick="openRecipeModal('${recipe.id}')" style="width: 100%; padding: 12px; background: #667eea; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; font-size: 14px;">
                    👁️ View Full Recipe
                </button>
            </div>
        `;
    });
    
    html += '</div>';
    container.innerHTML = html;
}

function saveSelectedRecipes() {
    localStorage.setItem('selectedRecipesThisWeek', JSON.stringify(selectedRecipesThisWeek));
}

function loadSelectedRecipes() {
    const saved = localStorage.getItem('selectedRecipesThisWeek');
    if (saved) {
        try {
            selectedRecipesThisWeek = JSON.parse(saved);
        } catch (e) {
            selectedRecipesThisWeek = [];
        }
    }
}

// ===================================
// INITIALIZE ON LOAD
// ===================================

document.addEventListener('DOMContentLoaded', () => {
    loadSelectedRecipes();
    initializeRecipeLibrary();
});

console.log('✅ Recipe Display UI loaded!');
